services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy_app
    ports:
      - "8000:8000"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4" ]
    depends_on:
      - redis
      - react-app

  react-app:
    build:
      context: ./clientARC
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
        
        
volumes:
  redis_data: